---
  - name: Install vault
    ansible.builtin.get_url:
      url: https://releases.hashicorp.com/vault/{{ version }}/vault_{{ version }}_linux_amd64.zip
      dest: /tmp/vault{{ version }}.zip
  
  - name: Unzip vault
    unarchive:
      src: /tmp/vault{{ version }}.zip
      dest: /usr/local/bin
      remote_src: true
    notify: Restart vault