---

  - name: Install Packages
    ansible.builtin.package:
      name: "{{item}}"
    with_items:
      - unzip
      - jq
  
  - name: Create vault Group
    group:
      name: "{{ group }}"
  
  - name: Create vault User
    user:
      name: "{{ user }}"
      group: "{{ group }}"
      groups: 
        - "{{ lets_encrypt_group }}"
  
  - name: Install vault
    ansible.builtin.get_url:
      url: https://releases.hashicorp.com/vault/{{ version }}/vault_{{ version }}_linux_amd64.zip
      dest: /tmp/vault{{ version }}.zip
  
  - name: Unzip vault
    unarchive:
      src: /tmp/vault{{ version }}.zip
      dest: /usr/local/bin
      remote_src: true
    notify: Restart vault
  
  - name: Wipe vault Data
    file:
      path: "{{vault_data_dir}}"
      state: absent
    when: wipe_data
    notify: Restart vault
  
  - name: Create vault Directory
    file:
      path: "{{item}}"
      state: directory
      owner: vault
      group: vault
      mode: "0750"
    with_items: 
      - "{{ config_dir }}"
      - "{{vault_data_dir}}"
  
  - name: Add vault config
    template:
      src: config.hcl.j2
      dest: "{{ config_dir }}/config.hcl"
    notify: Restart vault
  
  - name: Add vault.Service
    template:
      src: vault.service.j2
      dest: /etc/systemd/system/vault.service
    notify: Restart vault
  